version: '2'
services:
  rethinkdb:
    image: rethinkdb
    volumes:
      - .:/usr/src/data
      - .:/usr/src/rethinkdb/data
    ports:
      - "8082:8080"
      - "28015:28015"
  web:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "8080:8080"
    depends_on:
      - rethinkdb
